-- ===========================================================
-- SCHEMA DELIVERYTECH - ATUALIZADO (NOVEMBRO 2025)
-- ===========================================================

-- Remoção das tabelas existentes (ordem reversa para evitar FK errors)
DROP TABLE IF EXISTS pedido_itens;
DROP TABLE IF EXISTS pedidos;
DROP TABLE IF EXISTS avaliacoes;
DROP TABLE IF EXISTS produtos;
DROP TABLE IF EXISTS restaurantes;
DROP TABLE IF EXISTS telefones;
DROP TABLE IF EXISTS clientes;
DROP TABLE IF EXISTS enderecos;
DROP TABLE IF EXISTS ceps;
DROP TABLE IF EXISTS cidades;
DROP TABLE IF EXISTS estados;

-- ===========================================================
-- ENDEREÇAMENTO
-- ===========================================================

-- ===== ESTADOS =====
CREATE TABLE estados (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome   VARCHAR(100) NOT NULL,
  uf  CHAR(2) NOT NULL UNIQUE
);

-- ===== CIDADES =====
CREATE TABLE cidades (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome       VARCHAR(100) NOT NULL,
  estado_id  BIGINT NOT NULL,
  CONSTRAINT fk_cidades_estado
    FOREIGN KEY (estado_id) REFERENCES estados(id)
);
CREATE INDEX idx_cidades_estado ON cidades (estado_id, nome);

-- ===== CEPS =====
CREATE TABLE ceps (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo      VARCHAR(9) NOT NULL UNIQUE,  -- formato 00000-000
  cidade_id   BIGINT NOT NULL,
  CONSTRAINT fk_ceps_cidade
    FOREIGN KEY (cidade_id) REFERENCES cidades(id)
);
CREATE INDEX idx_ceps_cidade ON ceps (cidade_id);

-- ===== ENDEREÇOS =====
CREATE TABLE enderecos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            VARCHAR(150) NOT NULL,     -- nome da rua
  logradouro VARCHAR(20)  NOT NULL,     -- enum (RUA, AVENIDA, TRAVESSA...)
  numero          VARCHAR(10)  NOT NULL,
  complemento     VARCHAR(50),
  bairro          VARCHAR(100) NOT NULL,
  cep_id          BIGINT       NOT NULL,
  latitude        DECIMAL(9,6),
  longitude       DECIMAL(9,6),
  CONSTRAINT fk_endereco_cep
    FOREIGN KEY (cep_id) REFERENCES ceps(id)
);
CREATE INDEX idx_endereco_cep ON enderecos (cep_id);

-- ===========================================================
-- CLIENTES
-- ===========================================================
CREATE TABLE clientes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            VARCHAR(120) NOT NULL,
  email           VARCHAR(120) NOT NULL,
  data_cadastro   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ativo           BOOLEAN NOT NULL DEFAULT TRUE,
  endereco_id     BIGINT,
  CONSTRAINT uk_clientes_email UNIQUE (email),
  CONSTRAINT fk_cliente_endereco FOREIGN KEY (endereco_id) REFERENCES enderecos(id)
);
CREATE INDEX idx_clientes_endereco ON clientes (endereco_id);

-- ===========================================================
-- TELEFONES
-- ===========================================================
CREATE TABLE telefones (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id  BIGINT NOT NULL,
  pais        VARCHAR(2) NOT NULL DEFAULT '55',
  ddd         VARCHAR(3) NOT NULL,
  numero      VARCHAR(15) NOT NULL,
  ativo       BOOLEAN DEFAULT TRUE,
  CONSTRAINT fk_telefone_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);
CREATE INDEX idx_telefones_cliente ON telefones (cliente_id);

-- ===========================================================
-- RESTAURANTES
-- ===========================================================
CREATE TABLE restaurantes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome               VARCHAR(120) NOT NULL,
  cnpj               VARCHAR(18)  NOT NULL,
  classe             VARCHAR(60), -- Enum ClasseRestaurante
  telefone           VARCHAR(20),
  email              VARCHAR(120),
  horario_abertura   TIME,
  horario_fechamento TIME,
  estado             VARCHAR(20) NOT NULL, -- Enum EstadoRestaurante
  data_cadastro      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ativo              BOOLEAN NOT NULL DEFAULT TRUE,
  endereco_id        BIGINT,
  CONSTRAINT uk_restaurantes_cnpj  UNIQUE (cnpj),
  CONSTRAINT fk_restaurante_endereco FOREIGN KEY (endereco_id) REFERENCES enderecos(id)
);
CREATE INDEX idx_restaurantes_endereco ON restaurantes (endereco_id);

-- ===========================================================
-- PRODUTOS
-- ===========================================================
CREATE TABLE produtos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            VARCHAR(120) NOT NULL,
  descricao       VARCHAR(255),
  categoria       VARCHAR(20)  NOT NULL,  -- Enum CategoriaProduto
  estoque         INT          NOT NULL,
  preco           DECIMAL(10,2) NOT NULL,
  ativo           BOOLEAN      NOT NULL,
  data_cadastro   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  restaurante_id  BIGINT       NOT NULL,
  CONSTRAINT fk_produtos_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes (id)
);
CREATE INDEX idx_produtos_restaurante ON produtos (restaurante_id, nome);

-- ===========================================================
-- AVALIAÇÕES
-- ===========================================================
CREATE TABLE avaliacoes (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id       BIGINT      NOT NULL,
  restaurante_id   BIGINT      NOT NULL,
  nota             VARCHAR(20) NOT NULL,   -- Enum NotaAvaliacao
  comentario       VARCHAR(500),
  data_avaliacao   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_avaliacoes_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
  CONSTRAINT fk_avaliacoes_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes (id),
  CONSTRAINT uk_cliente_restaurante UNIQUE (cliente_id, restaurante_id)
);
CREATE INDEX idx_avaliacoes_rest ON avaliacoes (restaurante_id, nota);
CREATE INDEX idx_avaliacoes_cli ON avaliacoes (cliente_id);

-- ===========================================================
-- PEDIDOS
-- ===========================================================
CREATE TABLE pedidos (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_pedido    VARCHAR(30)  NOT NULL UNIQUE,
  data_pedido      TIMESTAMP    NOT NULL,
  status           VARCHAR(20)  NOT NULL,  -- Enum StatusPedido
  valor_total      DECIMAL(10,2) NOT NULL,
  observacoes      VARCHAR(255),
  cliente_id       BIGINT       NOT NULL,
  restaurante_id   BIGINT       NOT NULL,
  CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
  CONSTRAINT fk_pedido_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
);
CREATE INDEX idx_pedidos_cliente ON pedidos (cliente_id);
CREATE INDEX idx_pedidos_rest ON pedidos (restaurante_id);
CREATE INDEX idx_pedidos_status ON pedidos (status);

-- ===========================================================
-- ITENS DO PEDIDO
-- ===========================================================
CREATE TABLE pedido_itens (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id       BIGINT       NOT NULL,
  produto_id      BIGINT       NOT NULL,
  quantidade      INT          NOT NULL,
  preco_unitario  DECIMAL(10,2) NOT NULL,
  subtotal        DECIMAL(10,2) NOT NULL,
  CONSTRAINT fk_item_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
  CONSTRAINT fk_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);
CREATE INDEX idx_itens_pedido ON pedido_itens (pedido_id);
CREATE INDEX idx_itens_produto ON pedido_itens (produto_id);

-- ===========================================================
-- FIM DO SCHEMA
-- ===========================================================
